import React, { useEffect, useMemo, useState } from 'react';
import { Image, Save, Sparkles, Upload } from 'lucide-react';
import { getCouponCreativeUrl, LinkCouponOffer, LinkCouponOfferProfile, LinkCouponRedemption, LinkProduct, updateCouponProfile, uploadCouponCreative } from '../services/linkWorldService.ts';
interface Props{offer:LinkCouponOffer|null;profile:LinkCouponOfferProfile|null;products:LinkProduct[];redemptions:LinkCouponRedemption[];onRefresh:()=>Promise<void>;}
const money=(v:number,c='CLP')=>new Intl.NumberFormat('es-CL',{style:'currency',currency:c,maximumFractionDigits:c==='CLP'?0:2}).format(Number(v||0));
export function CouponOfferProfilePanel({offer,profile,products,redemptions,onRefresh}:Props){
  const [form,setForm]=useState({product_id:'',headline:'',ad_copy:'',cta:'',audience:'',campaign_notes:'',learnings:'',next_improvement:''}); const [file,setFile]=useState<File|null>(null); const [creativeUrl,setCreativeUrl]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null);
  useEffect(()=>{setForm({product_id:profile?.product_id||'',headline:profile?.headline||'',ad_copy:profile?.ad_copy||'',cta:profile?.cta||'',audience:profile?.audience||'',campaign_notes:profile?.campaign_notes||'',learnings:profile?.learnings||'',next_improvement:profile?.next_improvement||''});setFile(null);setMessage(null);setCreativeUrl(null);if(profile?.creative_path)getCouponCreativeUrl(profile.creative_path).then(setCreativeUrl).catch(()=>setCreativeUrl(null));},[offer?.id,profile?.updated_at]);
  const offerProducts=useMemo(()=>products.filter(p=>p.business_id===offer?.business_id),[products,offer?.business_id]);
  const stats=useMemo(()=>{if(!offer)return{count:0,sales:0,link:0};const rs=redemptions.filter(r=>r.offer_id===offer.id&&r.status==='confirmed');return{count:rs.length,sales:rs.reduce((a,r)=>a+Number(r.sale_amount||0),0),link:rs.reduce((a,r)=>a+Number(r.total_link_due||0),0)};},[offer,redemptions]);
  if(!offer)return <section className="bg-[#fffdf7] border border-[#e9e2d3] rounded-2xl p-5 text-xs text-[#66685f]">Crea o selecciona un beneficio para abrir su ficha comercial.</section>;
  const save=async()=>{setBusy(true);setMessage(null);try{let creative_path=profile?.creative_path||null,creative_name=profile?.creative_name||null;if(file){const uploaded=await uploadCouponCreative(offer.id,file);creative_path=uploaded.path;creative_name=uploaded.name;}await updateCouponProfile({...form,offer_id:offer.id,product_id:form.product_id||null,creative_path,creative_name});await onRefresh();setMessage('Ficha guardada.');}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
  return <section className="bg-[#fffdf7] border border-[#e9e2d3] rounded-2xl p-5"><div className="flex flex-col xl:flex-row xl:items-start justify-between gap-4"><div><div className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#66685f]">Ficha del beneficio</div><h3 className="text-xl font-bold mt-1">{offer.name}</h3><p className="text-xs text-[#66685f] mt-1">Aquí vive el producto comercial: cómo se presenta, qué pieza usamos y qué aprendemos.</p></div><div className="grid grid-cols-3 gap-2 min-w-[330px]"><div className="p-3 rounded-xl bg-[#f4f0e6]"><div className="text-lg font-bold">{stats.count}</div><div className="text-[9px]">consumos</div></div><div className="p-3 rounded-xl bg-[#f4f0e6]"><div className="text-sm font-bold">{money(stats.sales,offer.currency)}</div><div className="text-[9px]">ventas</div></div><div className="p-3 rounded-xl bg-[#11120f] text-white"><div className="text-sm font-bold text-[#d8ff58]">{money(stats.link,offer.currency)}</div><div className="text-[9px]">LINK</div></div></div></div>
  <div className="grid xl:grid-cols-[1.25fr_.75fr] gap-4 mt-5"><div className="space-y-3"><div className="grid sm:grid-cols-2 gap-3"><label><span className="text-[9px] uppercase text-[#66685f]">Producto del ecosistema</span><select value={form.product_id} onChange={e=>setForm(f=>({...f,product_id:e.target.value}))} className="mt-1 w-full px-3 py-2.5 rounded-xl border border-[#e9e2d3] bg-white text-xs"><option value="">Sin producto asociado</option>{offerProducts.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><span className="text-[9px] uppercase text-[#66685f]">Público</span><input value={form.audience} onChange={e=>setForm(f=>({...f,audience:e.target.value}))} placeholder="Ej: huéspedes brasileños 35+" className="mt-1 w-full px-3 py-2.5 rounded-xl border border-[#e9e2d3] bg-white text-xs"/></label></div><label className="block"><span className="text-[9px] uppercase text-[#66685f]">Titular comercial</span><input value={form.headline} onChange={e=>setForm(f=>({...f,headline:e.target.value}))} placeholder="La promesa principal del beneficio" className="mt-1 w-full px-3 py-2.5 rounded-xl border border-[#e9e2d3] bg-white text-xs"/></label><label className="block"><span className="text-[9px] uppercase text-[#66685f]">Texto de publicidad</span><textarea rows={3} value={form.ad_copy} onChange={e=>setForm(f=>({...f,ad_copy:e.target.value}))} placeholder="Copy que acompaña la pieza" className="mt-1 w-full px-3 py-2.5 rounded-xl border border-[#e9e2d3] bg-white text-xs"/></label><label className="block"><span className="text-[9px] uppercase text-[#66685f]">Llamado a la acción</span><input value={form.cta} onChange={e=>setForm(f=>({...f,cta:e.target.value}))} placeholder="Ej: Usa tu cupón hoy" className="mt-1 w-full px-3 py-2.5 rounded-xl border border-[#e9e2d3] bg-white text-xs"/></label><label className="block"><span className="text-[9px] uppercase text-[#66685f]">Notas de campaña</span><textarea rows={2} value={form.campaign_notes} onChange={e=>setForm(f=>({...f,campaign_notes:e.target.value}))} placeholder="Dónde se publicó, contexto, observaciones" className="mt-1 w-full px-3 py-2.5 rounded-xl border border-[#e9e2d3] bg-white text-xs"/></label></div>
  <div className="space-y-3"><div className="rounded-2xl border border-[#e9e2d3] bg-[#f8f5ed] p-4 min-h-52 flex flex-col justify-center">{creativeUrl?<><a href={creativeUrl} target="_blank" rel="noreferrer" className="text-center"><Image className="w-8 h-8 mx-auto mb-2"/><div className="text-xs font-semibold">{profile?.creative_name||'Abrir pieza guardada'}</div><div className="text-[10px] text-[#66685f] mt-1">Abrir publicidad</div></a></>:<><Upload className="w-8 h-8 mx-auto mb-2"/><div className="text-xs text-center text-[#66685f]">Todavía no hay una pieza publicitaria guardada.</div></>}<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf,video/mp4,video/quicktime" onChange={e=>setFile(e.target.files?.[0]||null)} className="mt-4 text-[10px]"/>{file&&<div className="text-[10px] mt-2">{file.name}</div>}</div><label className="block"><span className="text-[9px] uppercase text-[#66685f]">Qué aprendimos</span><textarea rows={3} value={form.learnings} onChange={e=>setForm(f=>({...f,learnings:e.target.value}))} placeholder="Qué funcionó / qué no" className="mt-1 w-full px-3 py-2.5 rounded-xl border border-[#e9e2d3] bg-white text-xs"/></label><label className="block"><span className="text-[9px] uppercase text-[#66685f]">Próxima mejora</span><textarea rows={2} value={form.next_improvement} onChange={e=>setForm(f=>({...f,next_improvement:e.target.value}))} placeholder="Qué cambiaremos en la siguiente versión" className="mt-1 w-full px-3 py-2.5 rounded-xl border border-[#e9e2d3] bg-white text-xs"/></label></div></div>
  <div className="flex items-center justify-between gap-3 mt-4"><div className="text-[10px] text-[#66685f] flex items-center gap-2"><Sparkles className="w-3.5 h-3.5"/>Versión {profile?.version||1} · cada guardado deja registro de evolución.</div><button onClick={save} disabled={busy} className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-[#11120f] text-[#d8ff58] text-xs font-semibold disabled:opacity-50"><Save className="w-3.5 h-3.5"/>{busy?'Guardando…':'Guardar ficha'}</button></div>{message&&<div className="mt-3 text-xs text-[#66685f]">{message}</div>}</section>;
}
