import React, { useMemo, useState } from 'react';
import { Flame, Pin, Snowflake, ThermometerSun } from 'lucide-react';
import { LinkBusiness, LinkLeadWorkboard, setLeadPriority } from '../services/linkWorldService.ts';

interface Props { leads: LinkLeadWorkboard[]; businesses: LinkBusiness[]; onRefresh: () => Promise<void>; onOpenLead: (identityId: string) => void; }
const stageLabel=(stage:string)=>({new:'Nuevo',contacted:'Contactado',qualified:'Calificado',proposal:'Propuesta',won:'Ganado',lost:'Perdido',paused:'Pausado'} as Record<string,string>)[stage]||stage.replaceAll('_',' ');
const relevanceLabel=(state:LinkLeadWorkboard['relevance_state'])=>({hot:'Caliente',warm:'Vigente',cooling:'Enfriándose',cold:'Frío',historical:'Histórico'} as Record<string,string>)[state];
const monthLabel=(value:string)=>new Intl.DateTimeFormat('es-CL',{month:'long',year:'numeric'}).format(new Date(value+'T12:00:00'));

export function LeadDashboard({leads,businesses,onRefresh,onOpenLead}:Props){
  const [month,setMonth]=useState('all'); const [business,setBusiness]=useState('all'); const [stage,setStage]=useState('active'); const [relevance,setRelevance]=useState('all'); const [sort,setSort]=useState<'priority'|'recent'|'oldest'>('priority'); const [busy,setBusy]=useState<string|null>(null);
  const months=useMemo(()=>[...new Set(leads.map(l=>String(l.lead_month).slice(0,10)))].sort().reverse(),[leads]);
  const filtered=useMemo(()=>leads.filter(l=>{
    if(month!=='all'&&String(l.lead_month).slice(0,10)!==month)return false;
    if(business!=='all'&&(l.business_id||'none')!==business)return false;
    if(stage==='active'&&['won','lost'].includes(l.stage))return false;
    if(stage!=='all'&&stage!=='active'&&l.stage!==stage)return false;
    if(relevance!=='all'&&l.relevance_state!==relevance)return false;
    return true;
  }).sort((a,b)=>{
    if(a.pinned!==b.pinned)return Number(b.pinned)-Number(a.pinned);
    if(sort==='recent')return +new Date(b.last_activity_at)-+new Date(a.last_activity_at);
    if(sort==='oldest')return b.days_idle-a.days_idle;
    return b.effective_priority-a.effective_priority;
  }),[leads,month,business,stage,relevance,sort]);
  const counts=useMemo(()=>({hot:leads.filter(l=>l.relevance_state==='hot'&&!['won','lost'].includes(l.stage)).length,cooling:leads.filter(l=>l.relevance_state==='cooling').length,cold:leads.filter(l=>l.relevance_state==='cold').length,historical:leads.filter(l=>l.relevance_state==='historical').length}),[leads]);
  const setPriority=async(lead:LinkLeadWorkboard,value:string)=>{setBusy(lead.lead_id);try{await setLeadPriority({lead_id:lead.lead_id,manual_priority:value==='auto'?null:Number(value),pinned:lead.pinned,note:lead.priority_note||''});await onRefresh();}finally{setBusy(null);}};
  const togglePin=async(lead:LinkLeadWorkboard)=>{setBusy(lead.lead_id);try{await setLeadPriority({lead_id:lead.lead_id,manual_priority:lead.manual_priority,pinned:!lead.pinned,note:lead.priority_note||''});await onRefresh();}finally{setBusy(null);}};
  return <section className="bg-[#fffdf7] border border-[#e9e2d3] rounded-2xl overflow-hidden">
    <div className="p-5 border-b border-[#e9e2d3]"><div className="flex flex-col xl:flex-row xl:items-end justify-between gap-4"><div><div className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#66685f]">Atención comercial</div><h3 className="text-xl font-bold mt-1">Leads vivos</h3><p className="text-xs text-[#66685f] mt-1">La prioridad cae cuando no hay movimiento. Ganados y perdidos pasan a histórico.</p></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><div className="px-3 py-2 rounded-xl bg-[#fff2dc]"><div className="text-lg font-bold">{counts.hot}</div><div className="text-[9px]">calientes</div></div><div className="px-3 py-2 rounded-xl bg-[#f4f0e6]"><div className="text-lg font-bold">{counts.cooling}</div><div className="text-[9px]">enfriándose</div></div><div className="px-3 py-2 rounded-xl bg-[#eef4ff]"><div className="text-lg font-bold">{counts.cold}</div><div className="text-[9px]">fríos</div></div><div className="px-3 py-2 rounded-xl bg-[#f4f0e6]"><div className="text-lg font-bold">{counts.historical}</div><div className="text-[9px]">históricos</div></div></div></div>
    <div className="grid sm:grid-cols-2 xl:grid-cols-5 gap-2 mt-4"><select value={month} onChange={e=>setMonth(e.target.value)} className="px-3 py-2 rounded-xl border border-[#e9e2d3] bg-white text-xs"><option value="all">Todos los meses</option>{months.map(m=><option key={m} value={m}>{monthLabel(m)}</option>)}</select><select value={business} onChange={e=>setBusiness(e.target.value)} className="px-3 py-2 rounded-xl border border-[#e9e2d3] bg-white text-xs"><option value="all">Todos los negocios</option><option value="none">Sin negocio</option>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select value={stage} onChange={e=>setStage(e.target.value)} className="px-3 py-2 rounded-xl border border-[#e9e2d3] bg-white text-xs"><option value="active">Solo activos</option><option value="all">Todas las etapas</option><option value="new">Nuevos</option><option value="qualified">Calificados</option><option value="proposal">Propuesta</option><option value="won">Ganados</option><option value="lost">Perdidos</option></select><select value={relevance} onChange={e=>setRelevance(e.target.value)} className="px-3 py-2 rounded-xl border border-[#e9e2d3] bg-white text-xs"><option value="all">Toda relevancia</option><option value="hot">Calientes</option><option value="warm">Vigentes</option><option value="cooling">Enfriándose</option><option value="cold">Fríos</option><option value="historical">Históricos</option></select><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)} className="px-3 py-2 rounded-xl border border-[#e9e2d3] bg-white text-xs"><option value="priority">Mayor prioridad</option><option value="recent">Más reciente</option><option value="oldest">Más tiempo parado</option></select></div></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="bg-[#f8f5ed] border-b border-[#e9e2d3] text-[9px] uppercase tracking-wider text-[#66685f]"><tr><th className="p-3">Prioridad</th><th className="p-3">Persona</th><th className="p-3">Negocio</th><th className="p-3">Etapa</th><th className="p-3">Relevancia</th><th className="p-3">Sin movimiento</th><th className="p-3">Siguiente acción</th><th className="p-3">Control</th></tr></thead><tbody>{filtered.map(lead=><tr key={lead.lead_id} className="border-b border-[#f1ecdf] last:border-0 hover:bg-white"><td className="p-3"><div className="flex items-center gap-2">{lead.relevance_state==='hot'?<Flame className="w-4 h-4"/>:lead.relevance_state==='cold'?<Snowflake className="w-4 h-4"/>:<ThermometerSun className="w-4 h-4"/>}<strong className="text-lg">{lead.effective_priority}</strong></div></td><td className="p-3"><button onClick={()=>onOpenLead(lead.identity_id)} className="text-left"><div className="text-xs font-semibold">{lead.identity_label||'Identidad por resolver'}</div><div className="text-[9px] font-mono text-[#66685f]">{lead.person_universal_code||lead.universal_code}</div></button></td><td className="p-3 text-xs">{lead.business_name||'Sin negocio'}</td><td className="p-3"><span className="text-[10px] px-2 py-1 rounded-full bg-[#f4f0e6]">{stageLabel(lead.stage)}</span></td><td className="p-3"><span className="text-[10px] font-semibold">{relevanceLabel(lead.relevance_state)}</span></td><td className="p-3 text-xs">{lead.days_idle} día{lead.days_idle===1?'':'s'}</td><td className="p-3 max-w-[330px]"><div className="text-[10px] leading-4">{lead.recommended_action||(['won','lost'].includes(lead.stage)?'Queda como antecedente histórico.':'Crear próximo contacto verificable.')}</div></td><td className="p-3"><div className="flex items-center gap-1"><button title={lead.pinned?'Quitar fijación':'Fijar arriba'} disabled={busy===lead.lead_id} onClick={()=>togglePin(lead)} className={`p-2 rounded-lg border ${lead.pinned?'bg-[#11120f] text-[#d8ff58] border-[#11120f]':'border-[#e9e2d3]'}`}><Pin className="w-3.5 h-3.5"/></button><select disabled={busy===lead.lead_id} value={lead.manual_priority==null?'auto':String(lead.manual_priority)} onChange={e=>setPriority(lead,e.target.value)} className="px-2 py-2 rounded-lg border border-[#e9e2d3] bg-white text-[10px]"><option value="auto">Auto</option><option value="30">Baja</option><option value="50">Media</option><option value="75">Alta</option><option value="95">Urgente</option></select></div></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="p-8 text-center text-xs text-[#66685f]">No hay leads para estos filtros.</div>}</section>;
}
