import React,{useEffect,useMemo,useState} from 'react';
import {getSupabaseClient} from '../services/supabaseClient.ts';
type Prospect={id:string;name:string;category:string;city:string;role:string;status:string;priority:string;contact_name:string|null;contact_channel:string|null;contact_value:string|null;website:string|null;proposed_product:string|null;public_price:number|null;commercial_contribution:number|null;notes:string|null;next_action:string|null;next_action_at:string|null};
const stages=['investigar','contactar','contactado','diagnostico','propuesta','acuerdo','activo','descartado'];
const sectors=['Hotel','Hostal','Restaurante','Cafetería','Agencia de turismo','Operador turístico','Transporte','Spa y bienestar','Arriendo de bicicletas','Experiencia cultural','Comercio y artesanía','Otros'];
const fmt=(v:number)=>'$'+Math.round(v).toLocaleString('es-CL');
export function MerchantRadar(){
 const [data,setData]=useState<Prospect[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('todos'),[editing,setEditing]=useState<string|null>(null);
 const empty={name:'',category:'Hotel',city:'San Pedro de Atacama',role:'ambos',status:'investigar',priority:'media',contact_name:'',contact_channel:'',contact_value:'',website:'',proposed_product:'',public_price:'',commercial_contribution:'30',notes:'',next_action:'Contactar',next_action_at:''};
 const [form,setForm]=useState({...empty});
 const set=(key:string,value:string)=>setForm(p=>({...p,[key]:value}));
 const reload=async()=>{setBusy(true);setError('');const {data:d,error:e}=await getSupabaseClient().from('link_coupon_merchant_prospects').select('*').order('created_at',{ascending:false});if(e)setError(e.message);else setData((d||[]) as Prospect[]);setBusy(false)};
 useEffect(()=>{void reload()},[]);
 const filtered=useMemo(()=>data.filter(p=>(filter==='todos'||p.status===filter)&&[p.name,p.category,p.city,p.contact_name,p.proposed_product].join(' ').toLowerCase().includes(query.toLowerCase())),[data,query,filter]);
 const startEdit=(p:Prospect)=>{setEditing(p.id);setForm({name:p.name,category:p.category,city:p.city,role:p.role,status:p.status,priority:p.priority,contact_name:p.contact_name||'',contact_channel:p.contact_channel||'',contact_value:p.contact_value||'',website:p.website||'',proposed_product:p.proposed_product||'',public_price:p.public_price==null?'':String(p.public_price),commercial_contribution:p.commercial_contribution==null?'30':String(p.commercial_contribution),notes:p.notes||'',next_action:p.next_action||'',next_action_at:p.next_action_at||''})};
 const save=async()=>{if(!form.name.trim())return;setBusy(true);setError('');const values={...form,name:form.name.trim(),public_price:form.public_price?Number(form.public_price):null,commercial_contribution:form.commercial_contribution?Number(form.commercial_contribution):null,next_action_at:form.next_action_at||null};const db=getSupabaseClient().from('link_coupon_merchant_prospects');const {error:e}=editing?await db.update(values).eq('id',editing):await db.insert(values);if(e){setError(e.message);setBusy(false);return}setEditing(null);setForm({...empty});await reload()};
 const inp='w-full rounded-xl border border-[#e9e2d3] bg-white px-3 py-2.5 text-xs outline-none focus:border-[#11120f]';
 const field=(name:string,key:string,placeholder='')=><label className="block"><span className="text-[10px] text-[#66685f]">{name}</span><input className={inp+' mt-1'} value={(form as Record<string,string>)[key]} onChange={e=>set(key,e.target.value)} placeholder={placeholder}/></label>;
 const pct=Math.min(100,Math.max(0,Number(form.commercial_contribution)||0));const price=Number(form.public_price)||0;const link=price*Math.max(0,pct-20)/100;
 return <div className="space-y-5">
 <div className="flex flex-wrap items-end justify-between gap-3"><div><div className="font-mono text-[10px] uppercase tracking-widest text-[#66685f]">LINK Cupones · MAR</div><h2 className="text-2xl font-bold">Radar de comercios</h2><p className="text-sm text-[#66685f]">Investigar → contactar → acordar → activar. Un prospecto no es todavía un negocio afiliado.</p></div><button onClick={()=>void reload()} className="rounded-xl border border-[#e9e2d3] bg-white px-4 py-2 text-xs">Actualizar</button></div>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Prospectos',data.length],['Por contactar',data.filter(x=>['investigar','contactar'].includes(x.status)).length],['Negociando',data.filter(x=>['contactado','diagnostico','propuesta'].includes(x.status)).length],['Activos',data.filter(x=>x.status==='activo').length]].map(([n,v])=><div key={String(n)} className="p-4 rounded-2xl bg-[#fffdf7] border border-[#e9e2d3]"><div className="text-2xl font-bold">{v}</div><div className="text-[11px] text-[#66685f]">{n}</div></div>)}</div>
 <div className="grid xl:grid-cols-[1.65fr_1fr] gap-4">
 <div className="rounded-2xl border border-[#e9e2d3] bg-[#fffdf7] overflow-hidden"><div className="p-4 flex gap-2 border-b border-[#e9e2d3]"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar comercio, sector o producto…" className={inp}/><select value={filter} onChange={e=>setFilter(e.target.value)} className={inp+' max-w-40'}><option value="todos">Todos</option>{stages.map(s=><option key={s}>{s}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="bg-[#f4f0e6] text-[10px] uppercase text-[#66685f]"><tr><th className="p-3">Comercio</th><th className="p-3">Rol</th><th className="p-3">Estado</th><th className="p-3">Próxima acción</th><th className="p-3"></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} className="border-t border-[#f1ecdf]"><td className="p-3"><b>{p.name}</b><div className="text-[10px] text-[#66685f]">{p.category} · {p.city}</div></td><td className="p-3">{p.role}</td><td className="p-3">{p.status}</td><td className="p-3">{p.next_action||'Definir acción'}<div className="text-[10px] text-[#66685f]">{p.next_action_at||'Sin fecha'}</div></td><td className="p-3"><button onClick={()=>startEdit(p)} className="rounded-lg border px-3 py-1.5">Abrir</button></td></tr>)}</tbody></table>{!filtered.length&&<div className="p-8 text-center text-xs text-[#66685f]">Sin prospectos para este filtro. Puedes ingresar el primer comercio a la derecha.</div>}</div></div>
 <div className="rounded-2xl border border-[#e9e2d3] bg-[#fffdf7] p-5 space-y-3"><div className="flex justify-between items-center"><h3 className="font-bold">{editing?'Ficha de comercio':'Nuevo prospecto'}</h3>{editing&&<button className="text-xs underline" onClick={()=>{setEditing(null);setForm({...empty})}}>Nuevo</button>}</div>
 {field('Nombre del comercio *','name','Nombre del negocio')}
 <div className="grid grid-cols-2 gap-2"><label className="block"><span className="text-[10px] text-[#66685f]">Rubro</span><select value={form.category} onChange={e=>set('category',e.target.value)} className={inp+' mt-1'}>{sectors.map(s=><option key={s}>{s}</option>)}</select></label>{field('Ciudad','city')}</div>
 <div className="grid grid-cols-2 gap-2"><label><span className="text-[10px] text-[#66685f]">Rol</span><select className={inp+' mt-1'} value={form.role} onChange={e=>set('role',e.target.value)}><option value="ambos">Ambos</option><option value="ofertante">Ofertante</option><option value="distribuidor">Distribuidor</option></select></label><label><span className="text-[10px] text-[#66685f]">Prioridad</span><select className={inp+' mt-1'} value={form.priority} onChange={e=>set('priority',e.target.value)}>{['alta','media','baja'].map(s=><option key={s}>{s}</option>)}</select></label></div>
 <label><span className="text-[10px] text-[#66685f]">Estado comercial</span><select className={inp+' mt-1'} value={form.status} onChange={e=>set('status',e.target.value)}>{stages.map(s=><option key={s}>{s}</option>)}</select></label>
 <div className="grid grid-cols-2 gap-2">{field('Persona contacto','contact_name')}{field('Canal','contact_channel','WhatsApp, correo…')}</div>{field('Dato de contacto','contact_value')}{field('Sitio web','website')}
 {field('Producto o beneficio potencial','proposed_product')}
 <div className="grid grid-cols-2 gap-2">{field('Precio público (IVA incluido)','public_price','10000')}{field('Aporte comercial (%)','commercial_contribution','30')}</div>
 <div className="rounded-xl bg-[#f4f0e6] p-3 text-[11px] space-y-1"><div>Simulación sobre precio original · cliente 20% · LINK {Math.max(0,pct-20)}%</div><div><b>Cliente: {fmt(price*.8)}</b> · LINK: {fmt(link)}</div><div className="text-[#66685f]">Comercio: {fmt(price*(1-pct/100))}. Aporte de 30% = 20% cliente + 10% LINK; revisar otros aportes por acuerdo. La boleta se liquida aparte.</div></div>
 {field('Próxima acción','next_action')}<label><span className="text-[10px] text-[#66685f]">Fecha de seguimiento</span><input type="date" className={inp+' mt-1'} value={form.next_action_at} onChange={e=>set('next_action_at',e.target.value)}/></label><label><span className="text-[10px] text-[#66685f]">Notas de visita</span><textarea className={inp+' mt-1'} rows={3} value={form.notes} onChange={e=>set('notes',e.target.value)}/></label>
 <button disabled={busy||!form.name.trim()} onClick={()=>void save()} className="w-full rounded-xl bg-[#11120f] text-[#d8ff58] p-3 text-xs font-semibold disabled:opacity-40">{busy?'Guardando…':editing?'Guardar seguimiento':'Agregar al radar'}</button>{error&&<div className="text-xs text-red-700">{error}</div>}
 </div></div></div>
}